# Generated by Django 6.0.3 on 2026-09-08 12:43

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0003_user_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
