# version: '3.8'

services:
# # Uncomment to run django within docker
#   web:
#     build: .
#     command: python /code/manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - 8000:8000
#     depends_on:
#       - [db, ai-service]
#     environment:
#       - AI_SERVICE_URL=http://ai-service:8000
#     networks: [look-like-me-network]

    # SEE SOURCE: https://docs.docker.com/compose/gettingstarted/#step-4-enable-compose-watch-for-live-updates



  db:
    restart: always
    image: pgvector/pgvector:pg17 # more recent image of postgres that supports pgvector extension
    container_name: look-like-me-postgres 
    environment:
      - POSTGRES_USER=backend_dev
      - POSTGRES_PASSWORD=RvNt5Yjzhg08Ha7o
      - POSTGRES_DB=look_like_me_db
      # - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - postgres_data:/var/lib/postgresql
    networks: [look-like-me-network]

  ai-service:
    image: fatimahalzh/look-like-me-ai:latest
    ports:
      - "8001:8000"     # must publish a port — Django outside Docker can't see internal service names
                        # but when django is dockerized, remove this line and use the internal service name (ai-service) instead of localhost
    networks: [look-like-me-network]

networks:
  look-like-me-network:
    driver: bridge

  # pgadmin:
  #     image: dpage/pgadmin4
  #     container_name: demo-pgadmin #you can change this
  #     depends_on:
  #       - db
  #     ports:
  #       - "5051:80"
  #     environment:
  #       PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #       PGADMIN_DEFAULT_PASSWORD: root
  #     restart: always

volumes:
  postgres_data:
