# Generated by Django 6.0.3 on 2026-07-21 16:32

import pgvector.django.halfvec
import pgvector.django.indexes
from django.conf import settings
from django.db import migrations
from pgvector.django import VectorExtension



class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_image_uid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),

        migrations.AddField(
            model_name="image",
            name="embedding",
            field=pgvector.django.halfvec.HalfVectorField(
                blank=True,
                dimensions=2048,
                help_text="Vector embeddings of the image content",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="image",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=200,
                fields=["embedding"],
                m=16,
                name="embeddings_index",
                opclasses=["halfvec_cosine_ops"],
            ),
        ),
    ]
