# Generated by Django 6.0.3 on 2026-10-04 08:14

import django.core.validators
import matches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0004_rename_image_image_facial_image_alter_image_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="blurred_facial_image",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to="blurred_facial_images/",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="facial_image",
            field=models.ImageField(
                upload_to=matches.models.user_facial_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
    ]
