# Generated by Django 6.0.3 on 2026-08-14 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0002_blockeduser_uid_friendship_uid_matchinteraction_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchinteraction",
            name="deleted_at",
        ),
    ]
