# Generated by Django 6.0.3 on 2026-09-14 20:35

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0003_remove_matchinteraction_deleted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="friendship",
            name="unique_friendship_pair",
        ),
        migrations.AlterField(
            model_name="blockeduser",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(
                fields=["sender", "receiver", "status"],
                name="sender_receiver_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(
                django.db.models.functions.comparison.Least("sender", "receiver"),
                django.db.models.functions.comparison.Greatest("sender", "receiver"),
                name="asymmetric_unique_friendship_pair",
                violation_error_message="A friendship instance with this user already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.CheckConstraint(
                condition=models.Q(("sender", models.F("receiver")), _negated=True),
                name="self_friendship_constraint",
                violation_error_message="Cannot be friends with self!",
            ),
        ),
    ]
